version: "3.7"

services:
  mongo:
    image: "mongo:4.4.6"
    volumes:
      - ./database:/data/db
    networks:
      - kiz1_internal

  # Dockerfile exposes 5000 (gunicorn/flask default)
  backend:
    build: backend
    volumes:
      - ./backend:/backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SCRIPT_NAME=/sq/api
    networks:
      - kiz1_internal
    depends_on:
      - mongo

  # Dockerfile exposes 5173 (vite default)
  frontend:
    build: frontend
    volumes:
      - ./frontend/src:/frontend/src
    networks:
      - kiz1_internal
    depends_on:
      - backend
    environment:
      - NODE_ENV="dev"

#  nginx:
#    image: nginx
#    container_name: nginx
#    restart: always
#    ports:
#      - "443:443"
#    depends_on:
#      - backend
#      - frontend
#    volumes:
#      - ./nginx/auth/:/etc/nginx/conf.d
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - kiz1_internal
  
networks:
  kiz1_internal:
    external: true
